---
title: "GSS graph"
author: "Steve Vaisey"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(gssr)
library(tidyverse)
```

```{r, cache=TRUE}
data("gss_all")
```

```{r}
d <- gss_all |> 
  select(year, cappun, sex) |> 
  drop_na()

d |> count(cappun)

d <- d |> 
  mutate(support = if_else(cappun==2, 0L, 1L),
         female = if_else(sex==2, "Female", "Male")) 

sby <- d |> 
  group_by(year, female) |> 
  summarize(support = mean(support)*100)

ggplot(sby,
       aes(x = year,
           y = support,
           group = female,
           color = female)) +
  geom_point() +
  geom_line() +
  theme_minimal() +
  labs(title = "Support for Capital Punishment by Year and Sex",
       subtitle = "United States, 1974-2018",
       x = "Year",
       y = "% Supporting Capital Punishment",
       color = "",
       caption = "NOTE: Data from the US General Social Survey") +
  theme(legend.position = "top")
```

